server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: true   #开启基于http basic的认证
  user:
    name: user     #配置登录的账号
    password: 123  #密码